// ── LaTeX Conversion & Overleaf Integration ──

/**
 * Escape special LaTeX characters in text
 */
function escapeLatex(text) {
  if (!text) return "";
  return text
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/([&%$#_{}])/g, "\\$1")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/\|/g, "\\textbar{}")
    .replace(/</g, "\\textless{}")
    .replace(/>/g, "\\textgreater{}")
    .replace(/"/g, "''");
}

/**
 * Detect if a line is a section header (ALL CAPS, short, or common header patterns)
 */
function isSectionHeader(line) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.length < 2) return false;
  if (trimmed.length > 60) return false;

  const headers = [
    "education", "experience", "work experience", "professional experience",
    "skills", "technical skills", "projects", "certifications", "awards",
    "summary", "professional summary", "objective", "career objective",
    "contact", "contact information", "references", "publications",
    "achievements", "activities", "interests", "languages", "volunteer",
    "training", "courses", "additional information", "hobbies",
  ];

  if (headers.includes(trimmed.toLowerCase())) return true;
  if (trimmed === trimmed.toUpperCase() && trimmed.length < 40 && /[A-Z]/.test(trimmed)) return true;

  return false;
}

/**
 * Detect if a line looks like the person's name (first significant line, mixed case, no bullets)
 */
function isNameLine(line, lineIdx, lines) {
  if (lineIdx > 3) return false;
  const trimmed = line.trim();
  if (!trimmed || trimmed.length < 2 || trimmed.length > 50) return false;
  if (/^[•●▪▸\-–—]/.test(trimmed)) return false;
  if (/[@|]/.test(trimmed)) return false;
  for (let i = 0; i < lineIdx; i++) {
    if (lines[i].trim().length > 2 && !/^\s*$/.test(lines[i])) return false;
  }
  return true;
}

/**
 * Detect if a line is contact info (contains email, phone, linkedin, etc.)
 */
function isContactLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return false;
  if (/@/.test(trimmed)) return true;
  if (/\b\d{3}[\-.\s]?\d{3}[\-.\s]?\d{4}\b/.test(trimmed)) return true;
  if (/linkedin|github|portfolio|website|http/i.test(trimmed)) return true;
  if (/[|·•]/.test(trimmed) && trimmed.split(/[|·•]/).length >= 3) return true;
  return false;
}

/**
 * Detect bullet point lines
 */
function isBulletLine(line) {
  return /^\s*[•●▪▸\-–—]\s/.test(line);
}

/**
 * Convert resume plain text to LaTeX code with a clean, professional template
 */
export function convertResumeToLatex(resumeText) {
  if (!resumeText) return "";

  const lines = resumeText.split("\n");
  let name = "Your Name";
  let contactLines = [];
  let bodyLines = [];
  let headerDone = false;

  // Phase 1: Identify name and contact info
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    if (!headerDone) {
      if (isNameLine(line, i, lines)) {
        name = trimmed;
        continue;
      }
      if (isContactLine(line)) {
        contactLines.push(trimmed);
        continue;
      }
      if (isSectionHeader(line) || isBulletLine(line)) {
        headerDone = true;
        bodyLines.push(line);
        continue;
      }
      if (trimmed && !headerDone && i < 5) {
        contactLines.push(trimmed);
        continue;
      }
    }
    bodyLines.push(line);
  }

  // Phase 2: Build LaTeX document
  const latexParts = [];

  latexParts.push(`%-------------------------`);
  latexParts.push(`% Resume in LaTeX`);
  latexParts.push(`% Generated by Resume ATS Analyzer`);
  latexParts.push(`% Open in Overleaf to edit and compile`);
  latexParts.push(`%-------------------------`);
  latexParts.push(``);
  latexParts.push(`\\documentclass[letterpaper,11pt]{article}`);
  latexParts.push(``);
  latexParts.push(`\\usepackage[utf8]{inputenc}`);
  latexParts.push(`\\usepackage[T1]{fontenc}`);
  latexParts.push(`\\usepackage{lmodern}`);
  latexParts.push(`\\usepackage[margin=0.75in]{geometry}`);
  latexParts.push(`\\usepackage{titlesec}`);
  latexParts.push(`\\usepackage{enumitem}`);
  latexParts.push(`\\usepackage{hyperref}`);
  latexParts.push(`\\usepackage{xcolor}`);
  latexParts.push(``);
  latexParts.push(`% Colors`);
  latexParts.push(`\\definecolor{primary}{HTML}{2563EB}`);
  latexParts.push(`\\definecolor{darktext}{HTML}{1F2937}`);
  latexParts.push(`\\definecolor{graytext}{HTML}{6B7280}`);
  latexParts.push(``);
  latexParts.push(`% Hyperlink setup`);
  latexParts.push(`\\hypersetup{`);
  latexParts.push(`    colorlinks=true,`);
  latexParts.push(`    linkcolor=primary,`);
  latexParts.push(`    urlcolor=primary,`);
  latexParts.push(`}`);
  latexParts.push(``);
  latexParts.push(`% Section formatting`);
  latexParts.push(`\\titleformat{\\section}{`);
  latexParts.push(`  \\vspace{-6pt}\\scshape\\raggedright\\large\\bfseries\\color{darktext}`);
  latexParts.push(`}{}{0em}{}[\\color{primary}\\titlerule\\vspace{-5pt}]`);
  latexParts.push(``);
  latexParts.push(`% Remove page numbers`);
  latexParts.push(`\\pagestyle{empty}`);
  latexParts.push(``);
  latexParts.push(`% Custom commands`);
  latexParts.push(`\\newcommand{\\resumeSubheading}[4]{`);
  latexParts.push(`  \\vspace{-2pt}\\item`);
  latexParts.push(`    \\begin{tabular*}{\\textwidth}{l@{\\extracolsep{\\fill}}r}`);
  latexParts.push(`      \\textbf{#1} & \\textit{\\small #2} \\\\`);
  latexParts.push(`      \\textit{\\small#3} & \\textit{\\small #4} \\\\`);
  latexParts.push(`    \\end{tabular*}\\vspace{-7pt}`);
  latexParts.push(`}`);
  latexParts.push(``);
  latexParts.push(`\\newcommand{\\resumeItem}[1]{`);
  latexParts.push(`  \\item\\small{#1 \\vspace{-2pt}}`);
  latexParts.push(`}`);
  latexParts.push(``);
  latexParts.push(`\\begin{document}`);
  latexParts.push(``);
  latexParts.push(`%----------HEADING----------`);
  latexParts.push(`\\begin{center}`);
  latexParts.push(`    {\\Huge\\scshape\\bfseries ${escapeLatex(name)}} \\\\ \\vspace{4pt}`);

  // Contact line
  if (contactLines.length > 0) {
    const contactParts = contactLines
      .join(" | ")
      .split(/[|·•]/)
      .map((p) => p.trim())
      .filter(Boolean)
      .map((part) => {
        if (/@/.test(part)) {
          const email = part.match(/[\w.+-]+@[\w.-]+/)?.[0] || part;
          return `\\href{mailto:${email}}{${escapeLatex(part)}}`;
        }
        if (/linkedin/i.test(part)) {
          const url = part.match(/https?:\/\/[^\s]+/)?.[0] || part;
          return `\\href{${url}}{${escapeLatex(part)}}`;
        }
        if (/github/i.test(part)) {
          const url = part.match(/https?:\/\/[^\s]+/)?.[0] || part;
          return `\\href{${url}}{${escapeLatex(part)}}`;
        }
        if (/http/i.test(part)) {
          const url = part.match(/https?:\/\/[^\s]+/)?.[0] || part;
          return `\\href{${url}}{${escapeLatex(part)}}`;
        }
        return `\\small ${escapeLatex(part)}`;
      });
    latexParts.push(`    \\small ${contactParts.join(" $|$ ")}`);
  }

  latexParts.push(`\\end{center}`);
  latexParts.push(``);

  // Phase 3: Process body content
  let inItemize = false;

  for (let i = 0; i < bodyLines.length; i++) {
    const line = bodyLines[i];
    const trimmed = line.trim();

    if (!trimmed) {
      if (inItemize) {
        latexParts.push(`\\end{itemize}`);
        inItemize = false;
      }
      continue;
    }

    // Section headers
    if (isSectionHeader(line)) {
      if (inItemize) {
        latexParts.push(`\\end{itemize}`);
        inItemize = false;
      }
      latexParts.push(``);
      latexParts.push(`%-----------${trimmed.toUpperCase()}-----------`);
      latexParts.push(`\\section{${escapeLatex(trimmed)}}`);
      continue;
    }

    // Bullet points
    if (isBulletLine(line)) {
      const bulletText = trimmed.replace(/^[•●▪▸\-–—]\s*/, "");
      if (!inItemize) {
        latexParts.push(`\\begin{itemize}[leftmargin=0.15in, label={\\small\\textbullet}]`);
        inItemize = true;
      }
      latexParts.push(`    \\resumeItem{${escapeLatex(bulletText)}}`);
      continue;
    }

    // Regular text (could be a sub-heading like job title / company)
    if (inItemize) {
      latexParts.push(`\\end{itemize}`);
      inItemize = false;
    }

    // Check if next line is also non-bullet, non-header — might be a role/company pair
    const nextLine = i + 1 < bodyLines.length ? bodyLines[i + 1]?.trim() : "";
    const nextIsBullet = isBulletLine(bodyLines[i + 1] || "");
    const nextIsHeader = isSectionHeader(bodyLines[i + 1] || "");

    if (nextLine && !nextIsBullet && !nextIsHeader && !isSectionHeader(line)) {
      latexParts.push(`\\vspace{2pt}`);
      latexParts.push(`\\textbf{${escapeLatex(trimmed)}} \\\\`);
    } else {
      latexParts.push(`${escapeLatex(trimmed)} \\\\`);
    }
  }

  if (inItemize) {
    latexParts.push(`\\end{itemize}`);
  }

  latexParts.push(``);
  latexParts.push(`\\end{document}`);

  return latexParts.join("\n");
}

/**
 * Convert a single suggestion's "improved" text to a LaTeX snippet
 * Shows the before (commented out) and the after
 */
export function convertSuggestionToLatex(suggestion) {
  if (!suggestion) return "";

  const parts = [];
  parts.push(`%-------------------------`);
  parts.push(`% ATS Improvement Suggestion`);
  parts.push(`% Generated by Resume ATS Analyzer`);
  parts.push(`%-------------------------`);
  parts.push(``);
  parts.push(`\\documentclass[letterpaper,11pt]{article}`);
  parts.push(``);
  parts.push(`\\usepackage[utf8]{inputenc}`);
  parts.push(`\\usepackage[T1]{fontenc}`);
  parts.push(`\\usepackage{lmodern}`);
  parts.push(`\\usepackage[margin=1in]{geometry}`);
  parts.push(`\\usepackage{xcolor}`);
  parts.push(`\\usepackage[normalem]{ulem}`);
  parts.push(``);
  parts.push(`\\definecolor{oldtext}{HTML}{DC2626}`);
  parts.push(`\\definecolor{newtext}{HTML}{059669}`);
  parts.push(`\\definecolor{reasontext}{HTML}{6B7280}`);
  parts.push(``);
  parts.push(`\\begin{document}`);
  parts.push(``);
  parts.push(`\\section*{ATS Rewrite Suggestion}`);
  parts.push(``);
  parts.push(`\\subsection*{Original (replace this):}`);
  parts.push(`{\\color{oldtext}\\sout{${escapeLatex(suggestion.original)}}}`);
  parts.push(``);
  parts.push(`\\subsection*{Improved Version:}`);
  parts.push(`{\\color{newtext}\\textbf{${escapeLatex(suggestion.improved)}}}`);
  parts.push(``);
  parts.push(`\\subsection*{Why:}`);
  parts.push(`{\\color{reasontext}\\small ${escapeLatex(suggestion.reason)}}`);
  parts.push(``);
  parts.push(`\\vspace{10pt}`);
  parts.push(`\\noindent\\textit{Impact: +${suggestion.impact_points || 0} ATS points}`);
  parts.push(``);
  parts.push(`\\end{document}`);

  return parts.join("\n");
}

/**
 * Convert full resume text WITH applied improvements to LaTeX
 */
export function convertResumeWithImprovementsToLatex(resumeText, suggestions = []) {
  if (!resumeText) return "";

  let modifiedText = resumeText;

  // Apply all improvements to the text
  for (const s of suggestions) {
    if (s.original && s.improved && modifiedText.includes(s.original)) {
      modifiedText = modifiedText.replace(s.original, s.improved);
    }
  }

  return convertResumeToLatex(modifiedText);
}

/**
 * Open LaTeX code in Overleaf via their API.
 * Uses the Overleaf /docs endpoint which accepts a form POST with `snip` parameter.
 * Handles popup blockers by falling back to clipboard copy.
 *
 * @param {string} latexCode - The LaTeX source code
 * @returns {{ success: boolean, fallback?: boolean }} - Whether it opened or fell back to clipboard
 */
export function openInOverleaf(latexCode) {
  // Overleaf supports opening projects via form POST to /docs
  // We create a hidden form and submit it
  const form = document.createElement("form");
  form.method = "POST";
  form.action = "https://www.overleaf.com/docs";
  form.target = "_blank";
  form.style.display = "none";

  const input = document.createElement("input");
  input.type = "hidden";
  input.name = "snip";
  input.value = latexCode;
  form.appendChild(input);

  // Engine preference
  const engineInput = document.createElement("input");
  engineInput.type = "hidden";
  engineInput.name = "engine";
  engineInput.value = "pdflatex";
  form.appendChild(engineInput);

  document.body.appendChild(form);

  try {
    form.submit();
  } catch {
    // If form submission fails, fallback to clipboard
    navigator.clipboard.writeText(latexCode).catch(() => {});
    setTimeout(() => { document.body.removeChild(form); }, 100);
    return { success: false, fallback: true };
  }

  // Clean up
  setTimeout(() => {
    if (form.parentNode) {
      document.body.removeChild(form);
    }
  }, 2000);

  return { success: true };
}

/**
 * Copy LaTeX code to clipboard (fallback when Overleaf redirect is blocked)
 */
export async function copyLatexToClipboard(latexCode) {
  try {
    await navigator.clipboard.writeText(latexCode);
    return true;
  } catch {
    return false;
  }
}
